export interface Procedure {
  id: number;
  name: string;
  time: string;
  category: string;
}

export const procedures: Procedure[] = [
  // PHẦN 1. SIÊU ÂM
  { id: 1, category: "Siêu âm", name: "Siêu âm tuyến giáp", time: "2-10 phút" },
  { id: 2, category: "Siêu âm", name: "Siêu âm các tuyến nước bọt", time: "2-10 phút" },
  { id: 3, category: "Siêu âm", name: "Siêu âm cơ phần mềm vùng cổ mặt", time: "2-10 phút" },
  { id: 4, category: "Siêu âm", name: "Siêu âm hạch vùng cổ", time: "2-10 phút" },
  { id: 5, category: "Siêu âm", name: "Siêu âm đàn hồi nhu mô tuyến giáp", time: "2-10 phút" },
  { id: 6, category: "Siêu âm", name: "Siêu âm Doppler u tuyến, hạch vùng cổ", time: "5-30 phút" },
  { id: 7, category: "Siêu âm", name: "Siêu âm màng phổi", time: "2-10 phút" },
  { id: 8, category: "Siêu âm", name: "Siêu âm ổ bụng (gan, mật, tụy, lách, thận, bàng quang)", time: "2-10 phút" },
  { id: 9, category: "Siêu âm", name: "Siêu âm hệ tiết niệu nam (thận, tuyến thượng thận, bàng quang, tiền liệt tuyến)", time: "2-10 phút" },
  { id: 10, category: "Siêu âm", name: "Siêu âm hệ tiết niệu nữ (thận, tuyến thượng thận, bàng quang, tiền liệt tuyến)", time: "2-10 phút" },
  { id: 11, category: "Siêu âm", name: "Siêu âm tiền liệt tuyến qua trực tràng", time: "2-10 phút" },
  { id: 12, category: "Siêu âm", name: "Siêu âm thai (thai, rau thai, nước ối)", time: "5-30 phút" },
  { id: 13, category: "Siêu âm", name: "Siêu âm Doppler các khối u trong ổ bụng", time: "5-30 phút" },
  { id: 14, category: "Siêu âm", name: "Siêu âm Doppler gan, lách", time: "5-30 phút" },
  { id: 15, category: "Siêu âm", name: "Siêu âm Doppler mạch máu ổ bụng", time: "5-30 phút" },
  { id: 16, category: "Siêu âm", name: "Siêu âm Doppler động mạch thận", time: "5-30 phút" },
  { id: 17, category: "Siêu âm", name: "Siêu âm Doppler tĩnh mạch chậu, chủ dưới", time: "5-30 phút" },
  { id: 18, category: "Siêu âm", name: "Siêu âm tử cung buồng trứng qua đường bụng", time: "2-10 phút" },
  { id: 19, category: "Siêu âm", name: "Siêu âm tử cung, buồng trứng qua đường âm đạo", time: "2-10 phút" },
  { id: 20, category: "Siêu âm", name: "Siêu âm Doppler thai nhi 3 tháng đầu", time: "5-30 phút" },
  { id: 21, category: "Siêu âm", name: "Siêu âm Doppler thai nhi 3 tháng giữa", time: "5-30 phút" },
  { id: 22, category: "Siêu âm", name: "Siêu âm Doppler thai nhi 3 tháng cuối", time: "5-30 phút" },
  { id: 23, category: "Siêu âm", name: "Siêu âm khớp (gối, háng, khuỷu, cổ tay….)", time: "2-10 phút" },
  { id: 24, category: "Siêu âm", name: "Siêu âm phần mềm (da, tổ chức dưới da, cơ….)", time: "2-10 phút" },
  { id: 25, category: "Siêu âm", name: "Siêu âm Doppler động mạch chi dưới", time: "5-30 phút" },
  { id: 26, category: "Siêu âm", name: "Siêu âm Doppler tĩnh mạch chi dưới", time: "5-30 phút" },
  { id: 27, category: "Siêu âm", name: "Siêu âm tim, màng tim qua thành ngực", time: "5-30 phút" },
  { id: 28, category: "Siêu âm", name: "Siêu âm Doopler tim, van tim", time: "5-30 phút" },
  { id: 29, category: "Siêu âm", name: "Siêu âm tuyến vú hai bên", time: "2-10 phút" },
  { id: 30, category: "Siêu âm", name: "Siêu âm đàn hồi mô vú", time: "2-10 phút" },
  { id: 31, category: "Siêu âm", name: "Siêu âm tinh hoàn hai bên", time: "2-10 phút" },
  { id: 32, category: "Siêu âm", name: "Siêu âm Doppler tinh hoàn, mào tinh hoàn hai bên", time: "5-30 phút" },
  { id: 33, category: "Siêu âm", name: "Siêu âm dương vật", time: "2-10 phút" },
  { id: 34, category: "Siêu âm", name: "Siêu âm đàn hồi mô (gan, tuyến vú…)", time: "5-30 phút" },

  // PHẦN 2. CHỤP X-QUANG
  { id: 35, category: "X-quang", name: "Chụp X-quang sọ thẳng/nghiêng", time: "2-10 phút" },
  { id: 36, category: "X-quang", name: "Chụp X-quang mặt thẳng nghiêng", time: "2-10 phút" },
  { id: 37, category: "X-quang", name: "Chụp X-quang mặt thấp", time: "1-10 phút" },
  { id: 38, category: "X-quang", name: "Chụp X-quang mặt cao", time: "1-10 phút" },
  { id: 39, category: "X-quang", name: "Chụp X-quang sọ tiếp tuyến", time: "1-10 phút" },
  { id: 40, category: "X-quang", name: "Chụp X-quang hốc mắt thẳng nghiêng", time: "2-10 phút" },
  { id: 41, category: "X-quang", name: "Chụp X-quang Blondeau", time: "1-10 phút" },
  { id: 42, category: "X-quang", name: "Chụp X-quang Hirtz", time: "1-10 phút" },
  { id: 43, category: "X-quang", name: "Chụp X-quang hàm chếch một bên", time: "1-10 phút" },
  { id: 44, category: "X-quang", name: "Chụp X-quang xương chính mũi nghiêng", time: "1-10 phút" },
  { id: 45, category: "X-quang", name: "Chụp X-quang xương chính mũi tiếp tuyến", time: "1-10 phút" },
  { id: 46, category: "X-quang", name: "Chụp X-quang hố yên nghiêng", time: "1-10 phút" },
  { id: 47, category: "X-quang", name: "Chụp X-quang tai tư thế Chausse III", time: "1-10 phút" },
  { id: 48, category: "X-quang", name: "Chụp X-quang Schuller", time: "1-10 phút" },
  { id: 49, category: "X-quang", name: "Chụp X-quang Stenvers", time: "1-10 phút" },
  { id: 50, category: "X-quang", name: "Chụp X-quang khớp thái dương hàm", time: "1-10 phút" },
  { id: 51, category: "X-quang", name: "Chụp X-quang răng cận chóp (Periapical)", time: "1-10 phút" },
  { id: 52, category: "X-quang", name: "Chụp X-quang răng cánh cắn (Bite wing)", time: "1-10 phút" },
  { id: 53, category: "X-quang", name: "Chụp X-quang phim cắn (Occlusal)", time: "1-10 phút" },
  { id: 54, category: "X-quang", name: "Chụp X-quang mỏm trâm", time: "1-10 phút" },
  { id: 55, category: "X-quang", name: "Chụp X-quang cột sống cổ thẳng nghiêng", time: "2-10 phút" },
  { id: 56, category: "X-quang", name: "Chụp X-quang cột sống cổ chếch hai bên", time: "2-10 phút" },
  { id: 57, category: "X-quang", name: "Chụp X-quang cột sống cổ động, nghiêng 3 tư thế", time: "2-10 phút" },
  { id: 58, category: "X-quang", name: "Chụp X-quang cột sống cổ C1- C2", time: "1-10 phút" },
  { id: 59, category: "X-quang", name: "Chụp X-quang cột sống ngực thẳng nghiêng", time: "2-10 phút" },
  { id: 60, category: "X-quang", name: "Chụp X-quang cột sống ngực chếch hai bên", time: "2-10 phút" },
  { id: 61, category: "X-quang", name: "Chụp X-quang cột sống thắt lưng thẳng nghiêng", time: "2-10 phút" },
  { id: 62, category: "X-quang", name: "Chụp X-quang cột sống thắt lưng động, 4 tư thế", time: "2-10 phút" },
  { id: 63, category: "X-quang", name: "Chụp X-quang cột sống thắt lưng De Sèze", time: "1-10 phút" },
  { id: 64, category: "X-quang", name: "Chụp X-quang cột sống cùng cụt thẳng nghiêng", time: "2-10 phút" },
  { id: 65, category: "X-quang", name: "Chụp X-quang khớp cùng chậu thẳng", time: "1-10 phút" },
  { id: 66, category: "X-quang", name: "Chụp X-quang khớp cùng chậu chếch hai bên", time: "2-10 phút" },
  { id: 67, category: "X-quang", name: "Chụp X-quang khung chậu thẳng", time: "1-10 phút" },
  { id: 68, category: "X-quang", name: "Chụp X-quang xương đòn", time: "1-10 phút" },
  { id: 69, category: "X-quang", name: "Chụp X-quang khớp vai thẳng", time: "1-10 phút" },
  { id: 70, category: "X-quang", name: "Chụp X-quang khớp vai nghiêng", time: "1-10 phút" },
  { id: 71, category: "X-quang", name: "Chụp X-quang khớp vai chếch", time: "1-10 phút" },
  { id: 72, category: "X-quang", name: "Chụp X-quang xương bả vai thẳng nghiêng", time: "2-10 phút" },
  { id: 73, category: "X-quang", name: "Chụp X-quang xương cánh tay thẳng nghiêng", time: "2-10 phút" },
  { id: 74, category: "X-quang", name: "Chụp X-quang khớp khuỷu thẳng, nghiêng hoặc chếch", time: "2-10 phút" },
  { id: 75, category: "X-quang", name: "Chụp X-quang khớp khuỷu gập (Jones hoặc Coyle)", time: "1-10 phút" },
  { id: 76, category: "X-quang", name: "Chụp X-quang xương cẳng tay thẳng nghiêng", time: "2-10 phút" },
  { id: 77, category: "X-quang", name: "Chụp X-quang xương cổ tay thẳng, nghiêng hoặc chếch", time: "2-10 phút" },
  { id: 78, category: "X-quang", name: "Chụp X-quang xương bàn ngón tay thẳng, nghiêng", time: "2-10 phút" },
  { id: 79, category: "X-quang", name: "Chụp X-quang khớp háng thẳng hai bên", time: "2-10 phút" },
  { id: 80, category: "X-quang", name: "Chụp X-quang khớp háng nghiêng", time: "1-10 phút" },
  { id: 81, category: "X-quang", name: "Chụp X-quang xương đùi thẳng nghiêng", time: "2-10 phút" },
  { id: 82, category: "X-quang", name: "Chụp X-quang khớp gối thẳng, nghiêng hoặc chếch", time: "2-10 phút" },
  { id: 83, category: "X-quang", name: "Chụp X-quang xương bánh chè và khớp đùi bánh chè", time: "2-10 phút" },
  { id: 84, category: "X-quang", name: "Chụp X-quang xương cẳng chân thẳng nghiêng", time: "2-10 phút" },
  { id: 85, category: "X-quang", name: "Chụp X-quang xương cổ chân thẳng, nghiêng hoặc chếch", time: "2-10 phút" },
  { id: 86, category: "X-quang", name: "Chụp X-quang xương bàn, ngón chân thẳng, nghiêng hoặc chếch", time: "2-10 phút" },
  { id: 87, category: "X-quang", name: "Chụp X-quang xương gót thẳng nghiêng", time: "2-10 phút" },
  { id: 88, category: "X-quang", name: "Chụp X-quang ngực thẳng", time: "1-10 phút" },
  { id: 89, category: "X-quang", name: "Chụp X-quang ngực nghiêng", time: "1-10 phút" },
  { id: 90, category: "X-quang", name: "Chụp X-quang ngực chếch", time: "1-10 phút" },
  { id: 91, category: "X-quang", name: "Chụp X-quang xương ức thẳng, nghiêng", time: "2-10 phút" },
  { id: 92, category: "X-quang", name: "Chụp X-quang khớp ức đòn thẳng chếch", time: "2-10 phút" },
  { id: 93, category: "X-quang", name: "Chụp X-quang đỉnh phổi ưỡn", time: "1-10 phút" },
  { id: 94, category: "X-quang", name: "Chụp X-quang thực quản cổ nghiêng", time: "5-15 phút" },
  { id: 95, category: "X-quang", name: "Chụp X-quang bụng không chuẩn bị thẳng hoặc nghiêng", time: "1-10 phút" },
  { id: 96, category: "X-quang", name: "Chụp X-quang tuyến vú", time: "10-15 phút" },
  { id: 97, category: "X-quang", name: "Chụp X-quang thực quản dạ dày", time: "1-10 phút" },
  { id: 98, category: "X-quang", name: "Chụp X-quang đại tràng", time: "15-60 phút" },
  { id: 99, category: "X-quang", name: "Chụp X-quang tử cung vòi trứng", time: "30 phút" },

  // PHẦN 3: CHỤP CẮT LƠP VI TÍNH
  { id: 100, category: "CLVT", name: "Chụp CLVT sọ não không tiêm thuốc cản quang", time: "5-20 phút" },
  { id: 101, category: "CLVT", name: "Chụp CLVT sọ não có tiêm thuốc cản quang", time: "10-30 phút" },
  { id: 102, category: "CLVT", name: "Chụp CLVT hệ động mạch cảnh có tiêm thuốc cản quang", time: "10-40 phút" },
  { id: 103, category: "CLVT", name: "Chụp CLVT sọ não có dựng hình 3D", time: "10-30 phút" },
  { id: 104, category: "CLVT", name: "Chụp CLVT hàm - mặt không tiêm thuốc cản quang", time: "5-20 phút" },
  { id: 105, category: "CLVT", name: "Chụp CLVT hàm -mặt có tiêm thuốc cản quang", time: "10-30 phút" },
  { id: 106, category: "CLVT", name: "Chụp CLVT tai - xương đá không tiêm thuốc", time: "5-20 phút" },
  { id: 107, category: "CLVT", name: "Chụp CLVT tai - xương đá có tiêm thuốc cản quang", time: "10-30 phút" },
  { id: 108, category: "CLVT", name: "Chụp CLVT hàm mặt có dựng hình 3D", time: "10-30 phút" },
  { id: 109, category: "CLVT", name: "Chụp CLVT lồng ngực không tiêm thuốc cản quang", time: "5-20 phút" },
  { id: 110, category: "CLVT", name: "Chụp CLVT lồng ngực có tiêm thuốc cản quang", time: "10-40 phút" },
  { id: 111, category: "CLVT", name: "Chụp CLVT phổi độ phân giải cao", time: "5-20 phút" },
  { id: 112, category: "CLVT", name: "Chụp CLVT phổi liều thấp tầm soát u", time: "5-20 phút" },
  { id: 113, category: "CLVT", name: "Chụp CLVT nội soi ảo cây phế quản", time: "10-30 phút" },
  { id: 114, category: "CLVT", name: "Chụp CLVT động mạch phổi", time: "10-40 phút" },
  { id: 115, category: "CLVT", name: "Chụp CLVT động mạch chủ ngực", time: "10-40 phút" },
  { id: 116, category: "CLVT", name: "Chụp cắt lớp vi tính ổ bụng khảo sát mạch các tạng", time: "10-30 phút" },
  { id: 117, category: "CLVT", name: "Chụp cắt lớp vi tính ruột non (entero-scan) không dùng sonde, không tiêm thuốc cản quang", time: "5-20 phút" },
  { id: 118, category: "CLVT", name: "Chụp cắt lớp vi tính ruột non (entero-scan) không dùng sonde, có tiêm thuốc cản quang", time: "10-30 phút" },
  { id: 119, category: "CLVT", name: "Chụp cắt lớp vi tính ruột non (entero-scan) có dùng sonde, có tiêm thuốc cản quang", time: "10-30 phút" },
  { id: 120, category: "CLVT", name: "Chụp cắt lớp vi tính ruột non (entero-scan) có dùng sonde, không tiêm thuốc cản quang", time: "5-20 phút" },
  { id: 121, category: "CLVT", name: "Chụp cắt lớp vi tính đại tràng (colo-scan) dùng dịch hoặc hơi có nội soi ảo, không tiêm thuốc cản quang", time: "5-20 phút" },
  { id: 122, category: "CLVT", name: "Chụp cắt lớp vi tính đại tràng (colo-scan) dùng dịch hoặc hơi có nội soi ảo, có tiêm thuốc cản quang", time: "10-30 phút" },
  { id: 123, category: "CLVT", name: "Chụp CLVT động mạch chủ - chậu", time: "10-40 phút" },
  { id: 124, category: "CLVT", name: "Chụp CLVT cột sống cổ không tiêm thuốc cản quang", time: "5-20 phút" },
  { id: 125, category: "CLVT", name: "Chụp CLVT cột sống cổ có tiêm thuốc cản quang", time: "10-30 phút" },
  { id: 126, category: "CLVT", name: "Chụp CLVT cột sống ngực không tiêm thuốc cản quang", time: "5-20 phút" },
  { id: 127, category: "CLVT", name: "Chụp CLVT cột sống ngực có tiêm thuốc cản quang", time: "10-30 phút" },
  { id: 128, category: "CLVT", name: "Chụp CLVT cột sống thắt lưng không tiêm thuốc cản quang", time: "5-20 phút" },
  { id: 129, category: "CLVT", name: "Chụp CLVT cột sống thắt lưng có tiêm thuốc cản quang", time: "10-30 phút" },
  { id: 130, category: "CLVT", name: "Chụp CLVT khớp thường quy không tiêm thuốc cản quang", time: "5-20 phút" },
  { id: 131, category: "CLVT", name: "Chụp CLVT khớp thường quy có tiêm thuốc cản quang", time: "10-30 phút" },
  { id: 132, category: "CLVT", name: "Chụp CLVT khớp có tiêm thuốc cản quang vào ổ khớp", time: "10-40 phút" },
  { id: 133, category: "CLVT", name: "Chụp CLVT xương chi không tiêm thuốc cản quang", time: "5-20 phút" },
  { id: 134, category: "CLVT", name: "Chụp CLVT xương chi có tiêm thuốc cản quang", time: "10-30 phút" },
  { id: 135, category: "CLVT", name: "Chụp CLVT mạch máu chi trên", time: "10-40 phút" },
  { id: 136, category: "CLVT", name: "Chụp CLVT mạch máu chi dưới", time: "10-40 phút" },
  { id: 137, category: "CLVT", name: "Chụp cắt lớp vi tính hốc mắt không tiêm thuốc cản quang", time: "5-20 phút" },
  { id: 138, category: "CLVT", name: "Chụp cắt lớp vi tính hốc mắt có tiêm thuốc cản quang", time: "10-30 phút" },
  { id: 139, category: "CLVT", name: "Chụp cắt lớp vi tính bụng - tiểu khung thường quy không tiêm thuốc cản quang", time: "5-20 phút" },
  { id: 140, category: "CLVT", name: "Chụp cắt lớp vi tính bụng - tiểu khung thường quy có tiêm thuốc cản quang", time: "10-30 phút" },
];
